services:
  app:
    image: danila68/spring-app-tracker-v2:latest
    env_file: .env    # Load all variables from .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  frontend:
    image: ilyaletich12/react-tracker-client-v1-prod:latest
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

  postgres:
    image: postgres:15
    env_file: .env    # Load all variables from .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data:
  redis-data:
