spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver


  docker:
    compose:
      stop:
        command: down
  sql:
    init:
      mode: never

jwt:
  secret: 956PBFst1FguLr5irJD-aQ
  expirationMs: 100000
logging:
  level:
    org.springframework.data.jdbc: trace
#    org.springframework.security: trace
springdoc:
  api-docs:
    path: /api-docs
