spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver


  docker:
    compose:
      stop:
        command: down
  sql:
    init:
      mode: always

jwt:
  secret: e.eh7Nxr]zH1QwGP4;s'57@a}p|eW~^"iZNniT8opo,49/bJMs39sb[JDP6jD>#
  expirationMs: 100000
logging:
  level:
    org.springframework.data.jdbc: debug
    org.springframework.jdbc: debug
#    org.springframework.security: trace
springdoc:
  api-docs:
    path: /api-docs
encryption:
  key: YOUR_BASE64_ENCODED_KEY_HERE
  algorithm: AES