spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: danilakartuzov5@gmail.com
    password: ccosxltorqxvrbpr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#
#  docker:
#    compose:
#      stop:
#        command:
  sql:
    init:
      mode: never

jwt:
  secret: e.eh7Nxr]zH1QwGP4;s'57@a}p|eW~^"iZNniT8opo,49/bJMs39sb[JDP6jD>#
  expirationMs: 100000000
logging:
  level:
#    org.springframework.data.jdbc: debug
#    org.springframework.jdbc: debug
    org.springframework.security: trace
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
encryption:
  key: KtZG4c2YJo0rz0p21iTXV8YYUGvJMb30JQOkvpXpRk8=
  algorithm: AES
