spring:
  data:
    redis:
      host: redis
      port: 6379

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver


    init:
      mode: always
      schema-locations: classpath:schema.sql  # Explicit path
      platform: postgresql

  flyway:
    enabled: false

jwt:
  secret: ${JWT_SECRET}
  expirationMs: 100000000
logging:
  level:
#    org.springframework.data.jdbc: debug
#    org.springframework.jdbc: debug
#    org.springframework.security: trace
    org.springframework.data.redis: trace
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
encryption:
  key: ${ENCRYPTION_KEY}
  algorithm: AES
  admin: ${ADMIN_KEY}
